[project]
authors = [{ name = "Thorsten Vitt", email = "thorsten.vitt@uni-wuerzburg.de" }]
requires-python = ">=3.9,<4.0"
dependencies = [
  "requests<3.0.0,>=2.27.1",
  "tomlkit<1.0.0,>=0.10.2",
  "xdg<6.0.0,>=5.1.1",
  "typer<1.0.0,>=0.6.1",
  "durations<1.0.0,>=0.3.3",
  "python-dateutil<3.0.0,>=2.8.2",
  "pathlib2<3.0.0.0,>=2.3.7.post1; python_version < \"3.10\"",
]
name = "getrel"
version = "0.1.1"
description = "Downloader for github releases"

[project.optional-dependencies]
tui = [
  "rich<13.0.0,>=12.4.1",
  "questionary<2.0.0,>=1.10.0",
  "humanize<5.0.0,>=4.2.3",
  "python-magic<1.0.0,>=0.4.27",
]

[project.scripts]
getrel = "getrel:_main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.mypy]
implicit_optional = true

[dependency-groups]
dev = [
  "mypy>=1.17.1",
  "pre-commit>=4.3.0",
  "pyinstaller>=6.15.0",
  "pytest>=8.4.1",
  "types-pygments>=2.19.0.20250809",
  "types-python-dateutil>=2.9.0.20250809",
  "types-requests>=2.32.4.20250809",
]
